import { z } from "zod";
import {
  createAnyValidate,
  createEmailValidate,
  createNumberValidate,
  createPasswordValidate,
  createTextValidate,
  createUrlValidate,
  createDateTimeValidate,
  createSelectValidate,
  createCheckBoxValidate,
  createRadioValidate,
} from "@/utils/validation";

export const formSchema = z.object({
  any: createAnyValidate(),
  email: createEmailValidate({ name: "メールアドレス" }),
  number: createNumberValidate({ name: "", min: 0, max: 10 }),
  password: createPasswordValidate({
    name: "",
    min_length: 8,
    req_char: true,
    req_number: true,
    req_symbol: true,
  }),
  tel: createTextValidate({ input_type: "tel" }),
  url: createUrlValidate({}),
  date: createDateTimeValidate({}),
  week: createAnyValidate(),
  month: createAnyValidate(),
  datetimeLocal: createDateTimeValidate({}),
  time: createAnyValidate(),
  hidden: createAnyValidate(),
  color: createAnyValidate(),
  file: createAnyValidate(),
  range: createAnyValidate(),
  textarea: createTextValidate({}),
  select: createSelectValidate({}),
  checkbox: createCheckBoxValidate({}),
  checkbox2: createCheckBoxValidate({}),
  checkbox3: createCheckBoxValidate({ max: 1 }),
  checkbox4: createCheckBoxValidate({ min: 2 }),
  radiobuttons: createRadioValidate({}),
  radiobuttons2: createRadioValidate({}),
  radiobuttons3: createRadioValidate({}),
  radiobuttons4: createRadioValidate({}),
});
